// config/templates/integration/astro/react/src/components/react/button.tsx
import { useState } from "react"

const Button = () => {
  const [count, setCount] = useState<number>(0)
  const handleClick = () => {
    setCount((c) => c + 1)
    console.log("Count: ", count)
  }
  return <>
    <span>
      Count: {count}
    </span>
    <button type="button" onClick={handleClick}>
      Click me
    </button>
  </>
}
export default Button

// config/templates/integration/astro/vue/src/components/vue/button.vue
<script setup lang="ts">
import { ref } from "vue"

const count = ref<number>(0)

const handleClick = () => {
  count.value++
  console.log("Count: ", count.value)
}
</script>

<template>
  <div>
    <span>
      Count: {{ count }} 
    </span>

    <button @click="handleClick">Click me</button>
  </div>
</template>
